### ISSUE TITLE
Unable to install sample app on Ipad

### ISSUE THREAD

**Issue by karlcod531** [AuthorizeNet/inperson-sdk-ios#47]
When I try to debug the sample app on a real iPad to be able to test the chip reader, I get an error during compilation because Xcode could not find a provisioning profile for the app.

**Comment by ptaneja** [comment]
You need to get the apple developer account and create your own provisioning profile.

**Comment by karlcod531** [comment]
You are right. However, one thing to note is that by default the application is set to use the author's team, which may cause confusion for some. When I changed the team, I was able to install the sample app on my device.
