### ISSUE TITLE
Apple Mach-O Linker Error

### ISSUE THREAD

**Issue by Al33139** [AuthorizeNet/inperson-sdk-ios#50]
Hi,

I am getting this error after linking the static library to my project. I followed the steps from the instructions. Please let me know what I am missing.

Thanks,

--------------------------------------------------------------------
Apple Mach-O Linker Error
“_OBJC_CLASS_$_AuthNet”, reference from:
EMVLibrary/libAnetEMVLibrary.a
Linker command failed with exit code 1 (use -v to see invocation)
--------------------------------------------------------------------

**Comment by ptaneja** [comment]
Hello, 

@Al33139 Are you working on Simulator?

**Comment by Al33139** [comment]
I am trying to run it on the simulator iPhone SE.


On Jun 16, 2017, at 5:31 PM, Pankaj Taneja <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

@Al33139<https://github.com/al33139> Are you working on Simulator?

**Comment by ptaneja** [comment]
Our Framework doesn't work on Simulator.
