### ISSUE TITLE
Which method is called when credit card is swiped?

### ISSUE THREAD

**Issue by hiren43** [AuthorizeNet/inperson-sdk-ios#51]
This sdk is confusing. Which method is called when credit card is swiped? I'm not able to find that. And when exactly user will insert/swipe the card?

**Comment by ptaneja** [comment]
Hello,

Which reader do you own? 
https://partner.posportal.com/authorizenet/auth/

**Comment by hiren43** [comment]
Hi. Right now I'm holding Card Flight reader. I guess I cannot implement Authorize.net sdk with this reader. Am I correct? I will buy another reader which will support this sdk. So this inperson sdk doesn't support card reading functionality?

**Comment by ptaneja** [comment]
It does support card reader functionality but for the below two readers:
https://partner.posportal.com/authorizenet/auth/

**Comment by hiren43** [comment]
okay. So will you please tell me which method in this sdk will be called when card is swiped?

**Comment by ptaneja** [comment]
Depends on the reader you buy. If you buy AnywhereCommerce  reader then please refer EMV portion of the SDK. If you buy IDTech Shuttle then obtain the track data from IDTech Shuttle reader by integrating their reader and post it with the help of inperson-sdk or you can use our app
https://itunes.apple.com/us/app/authorize-net/id453104966?mt=8

**Comment by hiren43** [comment]
I'm developing my own application and want to use this SDK. So far I'm able to login and get session token. I'm also initialising AnetEMVManager instance but I'm stuck at 'AnetEMVTransactionRequest' step. Now let me get this correct. I have to initialise AnetEMVTransactionRequest object and give product information and price. Then I need to use [startEMVWithTransactionRequest:presentingViewController:completionBlock:andCancelActionBlock].
This will open its own screen to let user enter credit card information. Right? I don't need to write any code for credit card. Am I correct?

**Comment by ptaneja** [comment]
Right. This is only true if you own a AnywhereCommerce reader.

**Comment by hiren43** [comment]
Thank you for the clarification.

**Comment by hiren43** [comment]
Hey there, back again 😄 . Do I have to compulsory perform device login to make EMV transaction? I guess login device asks for AuthNet credentials. App will be used by our employees who should not know about AuthorizeNet credentials. Please shed some light on this.

**Comment by hiren43** [comment]
Please this is urgent. Reply ASAP. To be able to interact with API, we need session token. Is AuthNet credentials the only way of getting session token? We don't want to give AuthNet credentials to our employees who will be making this transactions.  Isn't there a way to use a permanent key (which is hardcoded into app) to authorise merchant account?

**Comment by ptaneja** [comment]
Yes, to use our system user must login with credentials to generate the session token.
