### ISSUE TITLE
Can I use transaction key instead of password to login the mobile device?

### ISSUE THREAD

**Issue by hiren43** [AuthorizeNet/inperson-sdk-ios#52]
Hello. I'm using this library for my iOS application which accepts card payments. I already have integrated code in my app but have some queries regarding authorisation with merchant account. I think it is compulsory to login the device using 'mobileDeviceLoginRequest' for performing transactions. This app will be used by our employees which must not know about the merchant credentials. So can't just I use API login id and transaction key to login the mobile device so it can perform transactions? I tried using transaction key in stead of password with no luck. I guess most of the SDKs don't need merchant credentials in the app, they just allow some key to authorise. How should I approach this?

**Comment by adavidw** [comment]
Here's a forum thread that can help explain: https://community.developer.authorize.net/t5/Integration-and-Testing/iOS-Device-Login-with-loginID-and-transactionKey/td-p/50244

**Comment by hiren43** [comment]
@adavidw  Thanks. But it didn't solve my problem. I already created thread. There is a loophole. Apps will be used by employees. So they must not know about the merchant credentials(login and password) else they can misuse it. I still am not able to understand the role of transaction key. We should be using that instead of merchant's login data.

**Comment by rhldr** [comment]
You should create additional users for each device in the Merchant Interface and grant them appropriate permissions but not make them account administrators.

**Comment by adavidw** [comment]
Hi @hiren43,

The transaction key is more like a master key for transaction processing. Anyone with the login ID and transaction key can perform any transaction. So, that's definitely not something you'd want to use as the authentication for this app. Instead, better to set up individual user credentials for each device/employee so that you can set different levels of rights, or deactivate individual users as needed.

**Comment by hiren43** [comment]
thank you for replying. I have created a new user and with new credentials, he is able to login to device(authenticate) now. But when do I need to use transaction key? While performing transaction, will it prompt user to enter transaction key? Can you explain that?

**Comment by brianmc** [comment]
No need to use the transaction key unless you have an application running on a server, i.e. not an environment where that transaction key could be compromised, like a phone or a client-side browser app.  TRansaction key is a shared secret and is intended for server-to-server API integrations.
