### ISSUE TITLE
uncaught exception 'NSInvalidArgumentException', reason: '+[NSString stringWithXMLTag:andValue:]: unrecognized selector sent to class

### ISSUE THREAD

**Issue by Al33139** [AuthorizeNet/inperson-sdk-ios#53]
I am getting the following error when trying to register.

I have added the libAnetEMVLibrary static library and the IOS required libraries:
AudioToolbox.framework * CoreAudio.framework * MediaPlayer.framework * AVFoundation.framework * CoreBluetooth.framework and libxml2

- (void) loginToGateway {
    
    [AuthNet authNetWithEnvironment:ENV_LIVE];
    
    MobileDeviceLoginRequest *mobileDeviceLoginRequest = [MobileDeviceLoginRequest mobileDeviceLoginRequest];
    
    mobileDeviceLoginRequest.anetApiRequest.merchantAuthentication.name = @"User name";
    mobileDeviceLoginRequest.anetApiRequest.merchantAuthentication.password = @"User password";
    mobileDeviceLoginRequest.anetApiRequest.merchantAuthentication.mobileDeviceId = @"unique mobile id";
    
    AuthNet *an = [AuthNet getInstance];
    
    [an setDelegate:self];
    
    // Process a mobile device login request.
    [an mobileDeviceLoginRequest: mobileDeviceLoginRequest];
}

Error:

+[NSString stringWithXMLTag:andValue:]: unrecognized selector sent to class 0x1b39b8ae8
2017-08-16 16:49:25.316886-0400 PingAnetT300[1088:777135] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSString stringWithXMLTag:andValue:]: unrecognized selector sent to class 0x1b39b8ae8'
*** First throw call stack:
(0x18d6d6fe0 0x18c138538 0x18d6dde34 0x18d6daf54 0x18d5d6d4c 0x100058ec8 0x10004d2bc 0x10005ac08 0x100049444 0x100040ef0 0x100040b48 0x193807ec0 0x193807a9c 0x19380e31c 0x19380b7b8 0x19387d224 0x193a857ec 0x193a8b1e0 0x193a9fd18 0x193a88474 0x18f27f884 0x18f27f6f0 0x18f27faa0 0x18d68542c 0x18d684d9c 0x18d6829a8 0x18d5b2da4 0x193872384 0x19386d058 0x1000413f0 0x18c5c159c)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by ptaneja** [comment]
Looks like Xcode not loading the categories.
You can try the following things:
1. Include -ObjC in the other linker flags of your project settings. 
2. Includes the files in Headers section. Open your project target go to Build Phases then Headers. Please refer to the attached file. 
3. Refer to the SampleAppWithStaticLibrary.
![screen shot 2017-08-16 at 4 40 06 pm](https://user-images.githubusercontent.com/958291/29389896-d1c259a0-82a1-11e7-96b0-90c259db4a9f.jpg)
